### ISSUE TITLE
Shortcuts don't work in chrome/ubuntu

### ISSUE THREAD

**Issue by SinaKarimi7** [mahdyar/telemark#15]
Nothing happens when pressing `Ctrl + Shift + S`. 

![image](https://user-images.githubusercontent.com/16350906/113566600-3e1bdd00-9622-11eb-9bd7-8df065ba59b4.png)

**Comment by mahdyar** [comment]
Hello @SinaKarimi7 and thank you for your report,
What desktop environment are you using?

**Comment by mahdyar** [comment]
@SinaKarimi7 Is the problem solved? If not, please let me know what desktop environment are you using?

**Comment by SinaKarimi7** [comment]
@mahdyar Thank you for your response. But it still doesn't work for me and nothing happens by hitting the shortcuts. How can I know what happens?

-----
```
OS: Ubuntu 18.04.5 LTS x86_64 
Kernel: 5.11.11-051111-generic
DE: GNOME 3.28.4 
BR: Google Chrome Version 89.0.4389.114 (Official Build) (64-bit)
```

**Comment by mahdyar** [comment]
> @mahdyar Thank you for your response. But it still doesn't work for me and nothing happens by hitting the shortcuts.
> How do I know what is happening?
> 
> ```
> OS: Ubuntu 18.04.5 LTS x86_64 
> Kernel: 5.11.11-051111-generic
> DE: GNOME 3.28.4 
> BR: Google Chrome Version 89.0.4389.114 (Official Build) (64-bit)
> ```

I recommend uninstalling and then installing the extension again, specially if you'd installed the extension before version 1.1 was released. Also If you have other chromium-based browsers (e.g: brave, chromium, opera, ...) installed, please let me know if it's not working there either.

If the problem still persists, since I can't reproduce the problem, I can't figure out what's causing it on my own, so please do the following steps:
1. Remove the extension.
2. Download the source code from [here](https://github.com/mahdyar/telemark/archive/refs/tags/v1.1.zip).
3. Enable Developer Mode. ([How?](https://developer.chrome.com/docs/extensions/mv2/faq/#faq-dev-01))
4. Drag and Drop the extracted folder from the 2nd step in `chrome://extensions/`.
5. Hit the shortcut buttons and See if there's any errors like this:
![image](https://user-images.githubusercontent.com/20593549/114301181-e9240f00-9ad8-11eb-873c-ad12c4535a12.png)
6. If not, right click on the extension popup logo, choose `inspect popup`, hit the shortcuts again, and check the console for any errors.
7. Share the errors here, if there was any.

Please keep me posted on the progress.

**Comment by SinaKarimi7** [comment]
I did these steps and pressed `Ctrl + Shift + S` several times on different web pages.
 I just see this in the console. Any idea?
![image](https://user-images.githubusercontent.com/16350906/114302853-36f04580-9ae0-11eb-946b-f162d9d07530.png)

**Comment by mahdyar** [comment]
> @mahdyar I did these steps and pressed `Ctrl + Shift + S` several times on different web pages.
>  I just see this in the console. Any idea?
> ![image](https://user-images.githubusercontent.com/16350906/114302853-36f04580-9ae0-11eb-946b-f162d9d07530.png)
Were you in 'chrome://extensions'?

**Comment by mahdyar** [comment]
> @mahdyar I did these steps and pressed `Ctrl + Shift + S` several times on different web pages.
> I just see this in the console. Any idea?
> ![image](https://user-images.githubusercontent.com/16350906/114302853-36f04580-9ae0-11eb-946b-f162d9d07530.png)

Not really, that's because you opened the popup in `chrome://` url which an extension does not have access to.

Can you please install [this](http://dev.mahdyar.me/telemark/telemark-dev.zip) one and try with `CTRL+SHIFT+K`?

**Comment by SinaKarimi7** [comment]
> > @mahdyar I did these steps and pressed `Ctrl + Shift + S` several times on different web pages.
> > I just see this in the console. Any idea?
> > ![image](https://user-images.githubusercontent.com/16350906/114302853-36f04580-9ae0-11eb-946b-f162d9d07530.png)
> 
> Not really, that's because you opened the popup in `chrome://` url which an extension does not have access to.
> 
> Can you please install [this](http://dev.mahdyar.me/telemark/telemark-dev.zip) one and try with `CTRL+SHIFT+K`?

I install that and It works with `Ctrl + Shift + K` :)

**Comment by mahdyar** [comment]
> > > @mahdyar I did these steps and pressed `Ctrl + Shift + S` several times on different web pages.
> > > I just see this in the console. Any idea?
> > > ![image](https://user-images.githubusercontent.com/16350906/114302853-36f04580-9ae0-11eb-946b-f162d9d07530.png)
> > 
> > 
> > Not really, that's because you opened the popup in `chrome://` url which an extension does not have access to.
> > Can you please install [this](http://dev.mahdyar.me/telemark/telemark-dev.zip) one and try with `CTRL+SHIFT+K`?
> 
> I install that and It works with `Ctrl + Shift + K` :)

Glad to hear that :) 
In addition to your problem, the shortcut won't work in edge either (#16).
I'll make a hotfix PR tonight, and It'll probably be available on chrome web store in a day or two.

**Comment by SinaKarimi7** [comment]
@mahdyar Well done!
 IMO, it's better to add a feature for the user to define shortcut in the popup.

**Comment by mahdyar** [comment]
> @mahdyar Well done!
> IMO, it's better to add a feature for the user to define shortcut in the popup.

Well, that's a good idea, but as you saw, most of the key bindings are already reserved and do things, so there are not many options for users to define their own.
Also please open a new issue for a feature request and let this be only for `Shortcuts don't work in chrome/ubuntu`. :)
